[project]
name = "student-dropout-enrolled-graduate-rate-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "harshal_kusalkar", email = "h41497254@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "catboost>=1.2.10",
    "dvc>=3.67.1",
    "dvc-s3>=3.3.0",
    "lightgbm>=4.7.0",
    "matplotlib>=3.11.1",
    "mlflow>=3.14,<4",
    "numpy>=2.5.2",
    "optuna>=4.9.0",
    "pandas>=2.2,<3",
    "scikit-learn>=1.9.0",
    "xgboost>=3.4.1",
]

[project.scripts]
student-dropout-enrolled-graduate-rate-prediction = "student_dropout_enrolled_graduate_rate_prediction:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mlflow>=1.27.0",
    "pytest>=9.1.1",
]
