DATA_PATHS:
  data_path: data/raw/student_academic_data/data.csv

TARGET:
  name: Target
  classes:
    - Dropout
    - Enrolled
    - Graduate

FEATURES:

  categorical:
    - Marital status
    - Application mode
    - Course
    - Previous qualification
    - Nacionality
    - Mother's qualification
    - Father's qualification
    - Mother's occupation
    - Father's occupation

  binary:
    - Daytime/evening attendance
    - Displaced
    - Educational special needs
    - Debtor
    - Tuition fees up to date
    - Gender
    - Scholarship holder
    - International

  numerical:
    - Application order
    - Previous qualification (grade)
    - Admission grade
    - Age at enrollment

    - Curricular units 1st sem (credited)
    - Curricular units 1st sem (enrolled)
    - Curricular units 1st sem (evaluations)
    - Curricular units 1st sem (approved)
    - Curricular units 1st sem (grade)
    - Curricular units 1st sem (without evaluations)

    - Curricular units 2nd sem (credited)
    - Curricular units 2nd sem (enrolled)
    - Curricular units 2nd sem (evaluations)
    - Curricular units 2nd sem (approved)
    - Curricular units 2nd sem (grade)
    - Curricular units 2nd sem (without evaluations)

    - Unemployment rate
    - Inflation rate
    - GDP

PREPROCESSING:
  numerical:
    imputer:
      strategy: median
    scaler:
      type: standard

  categorical:
    imputer:
      strategy: most_frequent
    encoder:
      type: onehot
      handle_unknown: ignore

  binary:
    imputer:
      strategy: most_frequent

DATA_SPLIT:
  test_size: 0.2
  random_state: 42
  stratify: true