preprocessing:
  drop_columns:

    # Redundant / low-importance features
    - Educational special needs
    - GDP
    - Nacionality
    - International
    - Displaced
    - Unemployment rate
    - Daytime/evening attendance
    - Curricular units 1st sem (credited)
    - Curricular units 1st sem (without evaluations)

    # Second semester features (data leakage)
    - Curricular units 2nd sem (credited)
    - Curricular units 2nd sem (enrolled)
    - Curricular units 2nd sem (evaluations)
    - Curricular units 2nd sem (approved)
    - Curricular units 2nd sem (grade)
    - Curricular units 2nd sem (without evaluations)
  
  target_col: Target
  target:
    - Dropout
    - Enrolled 
    - Graduate
  
data_split:
  test_size: 0.2
  random_state: 42

data_paths:
  data_dir_path: data


artifacts:
  model_path: artifacts/models/best_model.joblib
  encoder_path: artifacts/encoder.joblib
  feature_names_path: artifacts/feature_names.joblib
  data_validation_path: artifacts/reports/validation.json
  eval_result_path: artifacts/eval_result.json
  classification_report_path: artifacts/classification_report.joblib

processed_data:
  X_train_path: data/processed/X_train.csv
  X_test_path: data/processed/X_test.csv
  y_train_path: data/processed/y_train.npy
  y_test_path: data/processed/y_test.npy

model:
  name: LightGBM
  version: v1

training:
  random_state: 42
  n_jobs: -1

model_params:
  objective: multiclass
  boosting_type: gbdt
  metric: multi_logloss
  verbosity: -1

  n_estimators: 200
  learning_rate: 0.0813878228331522
  max_depth: 5
  num_leaves: 121
  min_child_samples: 23
  min_child_weight: 0.38065697834121526
  subsample: 0.9997833996022827
  subsample_freq: 6
  colsample_bytree: 0.7570918902810027
  reg_alpha: 0.04897016843787337
  reg_lambda: 0.06909577691783778
  min_split_gain: 0.5434142910423587

experiment:
  best_trial: 24
  cv_metric: f1_macro
  best_cv_score: 0.6739500714665354
    

