name: Model Training

on:
  workflow_dispatch:

jobs:

  train:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install UV
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --frozen

      - name: Pull dataset with DVC 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: uv run dvc pull

      - name: Run data pipeline
        run: uv run python -m src.pipelines.data_pipeline
      
      - name: Verify DVC data 
        run: |
          test -f data/raw/student_academic_data/data.csv
          echo "DVC data successfully pulled."